module.exports = {
  EDIT_ROOM: 'EDIT_ROOM',
  REQUEST_GAME_START: 'REQUEST_GAME_START',
  REQUEST_GAME_RESTART: 'REQUEST_GAME_RESTART',
  WIDGET_PRESSED: 'WIDGET_PRESSED',
  SEND_WIDGETS: 'SEND_WIDGETS',
  ISSUE_COMMAND: 'ISSUE_COMMAND',
  GAME_OVER: 'GAME_OVER',
  NEXT_LEVEL: 'NEXT_LEVEL',
  MOVE_STATUS: 'MOVE_STATUS',
  DISCONNECT: 'DISCONNECT',
  RIGHT_MOVE: 'RIGHT_MOVE',
  WRONG_MOVE: 'WRONG_MOVE',
  RERENDER_PAGE: 'RERENDER_PAGE'
}
