export default {
  REQUEST_GAME_START: 'REQUEST_GAME_START',
  WIDGET_PRESSED: 'WIDGET_PRESSED',
  SEND_WIDGETS: 'SEND_WIDGETS',
  ISSUE_COMMAND: 'ISSUE_COMMAND',
  GAME_OVER: 'GAME_OVER',
  NEXT_LEVEL: 'NEXT_LEVEL',
  MOVE_STATUS: 'MOVE_STATUS',
  DISCONNECT: 'DISCONNECT'
}
